on:
  push:
    tags:
    - 'v*'

jobs:
- preprelease:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Setup Nerdbank.GitVersioning
      run: dotnet tool install -g nbgv
    - name: Prepare Release
      run: nbgv prepare-release

    outputs:
      version: ${{ steps.version.outputs.version }}
  
- preprelease:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
    - 

